// <auto-generated />
using System;
using Canban.DB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Canban.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240918072400_UpdateDatime2")]
    partial class UpdateDatime2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Canban.DB.Models.BoardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Canban.DB.Models.ColumnModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Canban.DB.Models.StatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Canban.DB.Models.TaskHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MoveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoveBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("NewCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NewDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewName")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NewStarted")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewUsers")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OldColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("OldCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("OldDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldName")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("OldStarted")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldUsers")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskHistories");
                });

            modelBuilder.Entity("Canban.DB.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColumnId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Completed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Started")
                        .HasColumnType("TEXT");

                    b.Property<int?>("test")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Canban.DB.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskModelUserModel", b =>
                {
                    b.Property<int>("TaskModelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskModelsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TaskModelUserModel");
                });

            modelBuilder.Entity("Canban.DB.Models.BoardModel", b =>
                {
                    b.HasOne("Canban.DB.Models.UserModel", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Canban.DB.Models.ColumnModel", b =>
                {
                    b.HasOne("Canban.DB.Models.BoardModel", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("TaskModelUserModel", b =>
                {
                    b.HasOne("Canban.DB.Models.TaskModel", null)
                        .WithMany()
                        .HasForeignKey("TaskModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Canban.DB.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
